version: 0.0.0
name: chainlinkFeeds
description: Chainlink feeds
repository: https://github.com/Float-Capital/chainlink-feeds
networks:
  - id: 42161
    start_block: 100000
    contracts:
      - name: ArbFeeds
        address:
          - "0x4258e5D50d737CBBEA347f0115Ad166e234902D7"
          - "0x52716c109696C0229E18fDeadFf6f54B3b73784F"
          - "0x1b9749e06817433a34D7efAaa0a7f6a94a41E432"
          - "0xadBf1c8a244d537C343d771e2Fa897F3654a1Ae4"
          - "0x244ea8646Cc2342497dFD5D8f841f79e66e598cF"
          - "0x5E4C65194F6F33a8BF7E9B95F1D0Ca9d611F6D62"
          - "0x7DD7029668c78af259a27A7696d468a152F06E53"
          - "0xd0DA1FE3A35359564CB7561F6a6AA69A1eCEc8d5"
          - "0xF56e6cb49304c2AD4a7C416665b55a1424014B1F"
          - "0x78f28D363533695458696b42577D2e1728cEa3D1"
          - "0x7AAeE6aD40a947A162DEAb5aFD0A1e12BE6FF871"
          - "0x5d750CC68ff61E2D68930003f77241f7346ADc84"
          - "0x53368bC6a7eB4f4AF3d6974520FEba0295A5daAb"
          - "0x79DaA21a44D1415306Ec17C361e0090bdD4cFCbe"
          - "0x5D041081725468Aa43e72ff0445Fde2Ad1aDE775"
          - "0xbfc294070e8A7594cEAa6C564883E1F9222BC09b"
          - "0xb20bd22d3D2E5a628523d37b3DED569598EB649b"
          - "0x94cD888Bea0dE39DD0b41396a9311c5212635EB7"
          - "0x52df0481c6D2Ad7E50889AFd03C8ddd8413ac63d"
          - "0xa44BCD128E99188565c4849cdfFEea9C773f74ec"
          - "0xf6bACC7750c23A34b996A355A6E78b17Fc4BaEdC"
          - "0xc339c4c7c58cb1d964b7B66f846572D5C355441a"
          - "0xEC2E9000B487F28Fd03455f9277bE3c96a3180b2"
          - "0x5ab0B1e2604d4B708721bc3cD1ce962958b4297E"
          - "0x0e9b5c79e005a30bf3fbB4d8ccCB6B0082ac5a17"
          - "0xc195bA27455182e3Bb6F86dAB5838901604Ba72c"
          - "0x2489462e64Ea205386b7b8737609B3701047a77d"
          - "0x660e7aF290F540205A84dccC1F40D0269fC936F5"
          - "0x46de66F10343b59BAcc37dF9b3F67cD0CcC121A3"
          - "0x20CD97619A51d1a6f1910ce62d98Aceb9a13d5e6"
          - "0xf8C6DE435CF8d06897a4A66b21df623D06d2A761"
          - "0x2946220288DbBF77dF0030fCecc2a8348CbBE32C"
          - "0x44D3ab6c4b98A3F9f241E1753b2475ad7e502051"
          - "0x3c6AbdA21358c15601A3175D8dd66D0c572cc904"
          - "0x942d00008D658dbB40745BBEc89A93c253f9B882"
          - "0x3c8F2d5af2e0F5Ef7C23A08DF6Ad168ece071D4b"
          - "0xe4A492420eBdA03B04973Ed1E46d5fe9F3b077EF"
          - "0xFc06bB03a9e1D8033f87eA6A682cbd65477A43b9"
          - "0x20870D99455B6F9d7c0E6f2608245719d789ff53"
          - "0x0AAAFE4278AA9D4514552f2743cBFa5a5Bdce04b"
          - "0x3607e46698d218B3a5Cae44bF381475C0a5e2ca7"
          - "0x9b8DdcF800a7BfCdEbaD6D65514dE59160a2C9CC"
          - "0xa136978a2c8a92ec5EacC5179642AA2E1c1Eae18"
          - "0xeFc5061B7a8AeF31F789F1bA5b3b8256674F2B71"
          - "0xF6328F007A2FDc547875e24A3BC7e0603fd01727"
          - "0xCb35fE6E53e71b30301Ec4a3948Da4Ad3c65ACe4"
          - "0x0Ae17556F9698fC47C365A746AB9CddCB17F3809"
        handler: ./src/EventHandlers.ts
        events:
          - event:
              event AnswerUpdated(int256 indexed current, uint256 indexed roundId,
              uint256 updatedAt)
            requiredEntities:
              - name: "feed"
  - id: 56
    start_block: 7329479
    contracts:
      - name: BscFeeds
        address:
          - "0x5C8c6c45dcF57aEae4D7Ba4F613B6FC38EF7d18B"
          - "0x577971aa5f4cF0a7f905dB42d612072CfF65077d"
          - "0x6f3f35Cc510232E41179F9010Cf12b1B48538a91"
          - "0x6a6eb03007131EAe9D02f66289a82d784c4EeA50"
          - "0x3D524E10b4C798b94c0d3353C7235f2bA14A5892"
          - "0x621319Ec1f6AFcb4a9dd91DAB135a1C7E22F46a5"
          - "0x86EB1bb8c66F365Ea3df12a565a46cEA204f6283"
          - "0x6c9C9757F0478bC38Bf73ABdA27ac42864De0645"
          - "0x3ED241a1877D213F70d7DDcaeF5c4995b63ED88D"
          - "0xE0A34B8FC5e80C877fd568bd22b49E1BCa977B6F"
          - "0xD2528B74ca91Bb07B9bd9685ce533367C6fa657C"
          - "0x2f92dc0711AdA3dc255e2197e7c15C8aDC6b6537"
          - "0xb2B7c2d554F52dAeC37974b2E335c98cdA8cEB3A"
          - "0x8f8289E5CA9a4C867ec7A257b0E9Dd1132093E23"
          - "0x7935a51aDDaB8550D346FEEf34e02F67C9330109"
          - "0x370d7b33330d40c55e8e71aFD88eFB31E9Dcc620"
          - "0x2e9c2B44D3f5702D2654c20260E8e010656D9777"
          - "0xd690b2CF0D2bcBce51c4cE2dc46E02C508465c5c"
          - "0x916aaDaCeb786351c7e810C6a4E8071cf00CEeC8"
          - "0x5CeefEC70Fb4819B9CE2dEaa6355c77E3243e640"
          - "0x1255E2748A3A26b248d654B5194CdeFc4594b90A"
          - "0x09A183232a9184ae07CEee3c0401f7435D42efdF"
          - "0x000f46946d47647c04A5f10269e9084FB8c8637A"
          - "0xB4C0F8F07a5e5d870bC02457213809B9cb5F56C4"
          - "0x5C0F367A778857B36E88B553df132b232AC34901"
          - "0x0877689c510f099FB968906223ab0a3F556d4f2B"
          - "0x40B8039e1A5A831b493C15164228A1839dd5b62a"
          - "0xfC3069296a691250fFDf21fe51340fdD415a76ed"
          - "0x2813fAB00b38189AcB8D805A687222Ae1034D53a"
          - "0x4c935c5C9a6BADC0855AD3B5867BCFf90c8bD5eC"
          - "0x19Ec74fd763db58B77E6EC6b556B9c594ca67ABB"
          - "0xF1eed6F4A9006B3Cf8f547B36d055b97EF50DE8b"
          - "0xEFc3be9286c4aE5c712BaB1182204086Ba0c45B6"
          - "0xCE75B866Ec86Ac261Ea191F0BC7820FB296C2477"
          - "0xF9e6F8660649f9762E0a721D666B8B5931EBB994"
          - "0x2028b4a27c14263Ba00C75c42cfe524E705031F4"
          - "0x50204D36C231CD4F0De67545Cd1E36C01336e46b"
          - "0xB92B265908775B59517eC1fC6C6635f7E1D60f1D"
          - "0x80519EcaD69B8E43C6690b73554379BfdF0eF79E"
          - "0xFBd2fED777DaaB126041b193006DE529118Eaf95"
          - "0x5ba2B3A2a41141Aa55Fc72C40d6643aEE12BD0B6"
          - "0xf0EcE271b1c02128e30C5797C0D76b2c9c36ec17"
          - "0x8dbb48f934b02E891e19Ec09f76B54f3ED5f01Ee"
          - "0xC04121E448DAC0BA66c0C76b28b5512Cf08bD41A"
          - "0x94069ff23E3a962646638b2Bb44d4d7F664DCCbD"
          - "0x2dc202b56A03667cC240B290c2BE2b8453E89eA1"
          - "0xF1703b483822f12Bf0D84296F2266196Ca9C352b"
          - "0x0C1A3fa6Cc1a91F751A9232cC5D6Be9700a93Fc7"
          - "0x73D17dbB9d4d520Ca4D260c359994d8a2Aa4cDa3"
          - "0x0D5aB38D37A5B5427B971E10F99e8c06599260Af"
          - "0x0Ad45915fC60a08dEcD39D27ad69AC10966C82C0"
          - "0x5D22062a0f28C476091D7023E7D2a240bA7e6b96"
          - "0x4849167844B7c8074B3Da31332AA547a17877b63"
          - "0xe978DaA50D3A8574F139c1e3Fe5D511dDb323BC5"
          - "0x390B935CdB6fC4924D203a398DA160178efe7b8A"
          - "0xc0850B8587cffA166985fa397e8391fecA959f3f"
          - "0xE6Ff236A76594a9A1Da727cA42B29c7B3ac0d45A"
          - "0x6FfA7c72cCd821A4dB68FD75Ee465dd09AA8C088"
          - "0xAB05DFc2e4aF7fb1b512306e3E0a3617992BB6E2"
          - "0xd29cFB96e80fCBA432713B7aE5086a6718d4E046"
          - "0xD2a2976cdf5098971DaA56878212Cdb24Ecb0CbB"
          - "0x7008fDEd94a8Ce68D01FEB633C4D81C2be7a1B20"
          - "0xc98fb42526666963d2b43a1ca5C3dc04fe744cdb"
          - "0x481E278Bf87281CF12342A4302e799Bf8515b985"
          - "0xF78feB6c096117Bfb9283aa1eAc304449E04d374"
          - "0x38d0f1dfE37Aac059aD06B2d30Ef60AA537f0b05"
          - "0x673DA2F5eaE6860F7b1249e2CbCca433834a1EB3"
          - "0x761Eff952671395708f22c5a7d5673685277A5c3"
          - "0xC430481d7f5b670623c70420643AC5EfA0D7c95d"
          - "0x5Ff27E78AE8fc4C329De7064ebe7FEbdE859af0A"
          - "0x9c0Ab19514D52196B09B04294937ECEC2Dc69950"
          - "0x4d70d497CeF3674be370586230F9a2f4b30CFF11"
          - "0x8A73214adB7a23334371Cb7C0c6165973F45Cd42"
          - "0x3331b2d33E9a472f6b34C150D47017d75b4CD088"
          - "0xacBf98E423Bb8458397dF2d4Cc9eE031879Fd59F"
          - "0x0D14D66DcB20b9EC4e9679AC8E4775a314D2E298"
          - "0xd0A597FfC7075E1449eCE7fEaA9880488dDB34FD"
          - "0x178bA789e24A1d51E9Ea3Cb1Db3B52917963D71D"
          - "0x343FB6A2ED16509a934880Abc82d0251867B70f4"
          - "0x7E90d60D3207A96FAaBB895C9c7DeE2E2CaBa0Fd"
          - "0x52Bd76d61D59a4F4B740FD31B97aFaD6217F960D"
          - "0x0Cee6620d87FD023800795D565A71fE214777aeb"
          - "0x43c70DB4018857eB6c4D6aA40880f144033AEAf5"
          - "0x8d06D8b3a37D9A1BCA3df055bDdD07f1639af4E6"
          - "0xeC1Ca9c5Dd897F832CDe3D43BB041f5e01380757"
          - "0xD051e4050dAd55285EEDbC186095C0Ccb7054944"
          - "0xE0A0Bc15e8Cbe87e9b6307693A368085E164878a"
          - "0xa749834a844f2824e5E703F3243e290a963cE06d"
          - "0x36Eb75b819dF05FB868b16074dF1A9c4354082c0"
          - "0x7A6BB3a3C0C99bA43564017D7523a74BA0f7cB5d"
          - "0x76303936B9DF69474A57352765faCEca2bf9C7Ef"
          - "0x137924D7C36816E0DcAF016eB617Cc2C92C05782"
          - "0x066D0CD30f981a96e2fE4F958c5E7F4999BE0AdF"
          - "0xe17703A1819d23cF5977814B92021834feBd4eB3"
          - "0x0B67AD077Fa839F6737A1630c89eE1A1572989c6"
          - "0x678f2883BB67104273229463ddA15Ee841584b36"
          - "0x9eBB8330dff88F3D9E743E8240177cdCD3292103"
          - "0x7457f14cE4773EBEb1352D2774Ec384a54c2F665"
          - "0x586E5572217D68643E1de6a0d40Cb37B0961A11a"
          - "0x87a69a2988b33ea745008A47486890232630AABf"
        handler: ./src/EventHandlers.ts
        events:
          - event:
              event AnswerUpdated(int256 indexed current, uint256 indexed roundId,
              uint256 updatedAt)
            requiredEntities:
              - name: "feed"
  # - id: 10
  #   start_block: 2014079
  #   contracts:
  #     - name: OpFeeds
  #       address:
  #         - "0x6AA7cC6feA036Bd57f36E2b82878c15012c48771"
  #         - "0x615209a932768861908161cCCEfcCac9b582ACe8"
  #         - "0x28a6B219403c1Dac04172cBb8cC1aB8bF5925830"
  #         - "0xaE4c8567C942B974Af4A860380c99A8D03C6148E"
  #         - "0x7FeD35C1e4C303F272E4fcdF19865E85DfA44f72"
  #         - "0xAA75acE4575AbBE1D237D991a7461f497a56a8F0"
  #         - "0xCa80A73840718826a7A8b6b7216Bd5fDa12c121A"
  #         - "0x7c56d3650f9aCD992b3Aa635C04A311c54Ad264c"
  #         - "0x0d110cC7876d73c3C4190324bCF4C59416bBD259"
  #         - "0x034f1d70092e81b7738459f02F409a5c5c4b8189"
  #         - "0xaB544FDAD5F68f0F8e53284f942D76177635A3D6"
  #         - "0x5d101824C693C70a68FFc3CDb0Cc394F3a4fb9Ec"
  #         - "0xE67a10DA53Fcd59fae7e47F155c290cb5Defb4B0"
  #         - "0x3b06B9b3ead7Ec34AE67E2D7f73B128dA09C583a"
  #         - "0x4F6dFDFd4d68F68b2692E79f9e94796fC8015770"
  #         - "0xc2212835DE6cb9Ef5e26b04E64f7798472Ff2812"
  #         - "0x65F2c716937FB44b2C28417A7AfC2DACcF1C2D61"
  #         - "0x85A48ded8c35d82f8f29844e25dD51a70a23c93d"
  #         - "0x81cC0c227BF9bFB8088b14755DfcA65f7892203b"
  #         - "0xd1Cb03cc31caa72D34dba7eBE21897D9580c4AF0"
  #         - "0x584F57911b6EEDab5503E202f8e193663c9bd3DB"
  #         - "0x17D582034c038BaEb17A9E2A969d06f550d3586b"
  #         - "0xAc37790fF4aBf9483fAe2D1f62fC61fE6b8E4789"
  #         - "0xE18a4E99F019F92CD72E0C7C05599d76a89296Cd"
  #         - "0xe4391393205B6265585250E7A026103a0D1E168d"
  #         - "0x647dA0ebfD5314aF3Bd53eA40541c6B67169e6D0"
  #         - "0x0C1272d2aC652D10d03bb4dEB0D31F15ea3EAb2b"
  #         - "0x19dC743a5E9a73eefAbA7047C7CEeBc650F37336"
  #         - "0xbCe7579e241e5d676c2371Dc21891489dAcDA250"
  #         - "0x1C1245eEfB57d50F90EFc4070b508f4f24c3aB7A"
  #         - "0x02f5E9e9dcc66ba6392f6904D5Fcf8625d9B19C9"
  #         - "0xB6b7B9b2362F87F204f1CCadDD8832D3a0557dce"
  #         - "0x44f690526B76D91072fb0427B0A24b882E612455"
  #       handler: ./src/EventHandlers.ts
  #       events:
  #         - event:
  #             event AnswerUpdated(int256 indexed current, uint256 indexed roundId,
  #             uint256 updatedAt)
  #           requiredEntities:
  #             - name: "feed"
